# Generated by Django 3.2b1 on 2021-03-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
