# Generated by Django 3.2rc1 on 2021-03-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
